-- Приватний чат команди. Виконайте один раз у Supabase SQL Editor.
-- RLS перевіряє команду на сервері, тому клієнт не може прочитати чужі повідомлення.

create table if not exists public.team_messages (
  id bigint generated by default as identity primary key,
  team_id text not null,
  body text not null check (char_length(body) between 1 and 2000),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists team_messages_team_created_idx
  on public.team_messages (team_id, created_at desc);

alter table public.team_messages enable row level security;
grant select, insert on public.team_messages to authenticated;
grant usage, select on sequence public.team_messages_id_seq to authenticated;

drop policy if exists "Team can read own chat" on public.team_messages;
create policy "Team can read own chat"
on public.team_messages
for select
to authenticated
using (
  team_id = public.current_workspace_team_id()
);

drop policy if exists "Team can send to own chat" on public.team_messages;
create policy "Team can send to own chat"
on public.team_messages
for insert
to authenticated
with check (
  created_by = auth.uid()
  and team_id = public.current_workspace_team_id()
);
